/**
 * Semantic intent and synonym dictionary for Playground API search.
 * Bridges beginner ("dumb user") natural language questions and power-user technical keywords.
 */

export interface IntentSynonymMap {
  [keyOrPath: string]: string[];
}

export const searchSynonyms: IntentSynonymMap = {
  // General & Getting Started
  '/docs/introduction': [
    'what is playground api',
    'overview',
    'about',
    'free fake api',
    'mock backend',
    'features list',
    'how to start',
    'beginner guide',
    'jsonplaceholder alternative',
    'dummyjson alternative',
    'dummy backend',
    'sandbox intro',
  ],
  '/docs/quickstart': [
    '30 second quickstart',
    'how to use',
    'first request',
    'getting started',
    'tutorial',
    'curl test',
    'fetch example',
    'hello world',
    'easy start',
    'test api fast',
    'starter',
    'rapid test',
  ],
  '/docs/how-it-works': [
    'how sandboxing works',
    'why is my data saved',
    'how does it remember changes',
    'stateful mutations',
    'overlay records',
    'per session storage',
    'session cookie',
    'local id',
    'architecture',
    'persistent mock',
    'isolated data',
  ],
  '/docs/recipes': [
    'framework recipes',
    'react example',
    'nextjs tutorial',
    'vue integration',
    'angular code',
    'svelte fetch',
    'axios interceptor',
    'swr example',
    'react query',
    'tanstack query',
    'flutter dart',
    'android kotlin',
    'ios swift',
  ],
  '/docs/filtering': [
    'query filtering and relations',
    'how to filter',
    'search by user id',
    'get posts of user',
    'comments for post',
    'nested query',
    'sorting desc asc',
    '_sort',
    '_order',
    'limit page pagination',
    'cursor based pagination',
    'infinite scroll',
    'useinfinitequery react query',
    'tanstack query pagination',
    'useswrinfinite',
    'nextcursor',
    'hasmore',
    'find specific items',
    'relational sub resources',
  ],
  '/docs/errors': [
    'http status and errors',
    'test error 500',
    'simulate 404 not found',
    'make it fail',
    'error simulation',
    'status codes',
    '401 unauthorized',
    '403 forbidden',
    '422 unprocessable',
    '500 server error',
    'test error handling',
    'catch block',
  ],
  '/docs/comparisons': [
    'playground api vs alternatives',
    'vs jsonplaceholder',
    'vs dummyjson',
    'vs platzi fake api',
    'vs mockoon',
    'vs mirage js',
    'comparison table',
    'why choose playground api',
    'best mock api',
  ],
  '/docs/ai': [
    'ai agent knowledge and rules',
    'cursor rules',
    'windsurf instructions',
    'copilot prompt',
    'llms.txt',
    'prompt engineering',
    'agentic coding',
    'system prompt',
    'claude rules',
  ],

  // Features & Sandbox Tools
  '/docs/studio': [
    'interactive api studio',
    'test runner',
    'try it out',
    'send test request',
    'rest client in browser',
    'swagger style tester',
    'live request builder',
    'headers inspector',
    'payload tester',
    'gui tester',
  ],
  '/docs/chat': [
    'realtime chat and websockets',
    'websocket',
    'websockets',
    'socket.io',
    'socket io',
    'live chat simulation',
    'support bot',
    'typing indicator',
    'server sent events',
    'sse stream',
    'notifications stream',
    'live messaging',
    'chat studio',
    'ws://',
    'real-time messages',
  ],
  '/docs/inbox': [
    'virtual email and sms web inbox',
    'inbox',
    'mailbox',
    'virtual mailbox',
    'mailtrap alternative',
    'mock email sandbox',
    'otp verification code testing',
    'extract otp',
    'magic link testing',
    'sms testing mock',
    'email attachments cloudinary',
    'password reset test email',
    'welcome verification email',
    'test transaction emails',
    'send email mock',
    'send sms mock',
    'fake email server',
    'fake smtp',
    '2fa code test',
  ],
  '/docs/webhooks': [
    'outgoing webhooks',
    'webhook dispatcher',
    'webhook delivery inspector',
    'hmac signature',
    'x-playground-signature',
    'test webhooks ngrok',
    'webhook receiver',
    'retry webhook delivery',
    'post.created webhook',
    'event driven mock api',
    'webhook simulator',
  ],
  '/docs/simulation': [
    'network and chaos simulation',
    'slow down api',
    'simulate delay',
    'fake lag',
    'slow 3g network',
    'loading spinner test',
    'x-simulate-delay',
    'x-simulate-status',
    'x-simulate-chaos',
    'x-simulate-chaos-errors',
    '_delay parameter',
    '_status parameter',
    '_chaos parameter',
    '_ratelimit parameter',
    'x-simulate-ratelimit',
    'rate limit simulation',
    'simulate 429 too many requests',
    'retry-after header',
    'quota violation simulation',
    'rate limit countdown',
    'flaky connection',
    'chaos monkey',
    'react query retry test',
    'simulate random errors',
    'stochastic failure',
    'swr retry backoff',
  ],
  '/docs/export-import': [
    'snapshot import and export',
    'save sandbox state',
    'export json backup',
    'import test seed data',
    'share test scenario',
    'backup mutations',
    'restore database state',
    'qa test data fixture',
  ],
  '/docs/sandbox-sync': [
    'shareable sandbox urls',
    'share sandbox',
    'qr code sync',
    'scan qr code',
    'mobile testing',
    'cross device sync',
    '_sandbox query parameter',
    'team mock sharing',
    'share mock state',
    'reproduce bug state',
    'ios testing',
    'android testing',
    'phone sync',
  ],
  '/docs/stats': [
    'session quotas and stats',
    'my session info',
    'how many records created',
    'reset sandbox button',
    'clear all my changes',
    'my identity token',
    'quota limits',
    'copy session id',
    'delete session',
  ],
  '/docs/showcase': [
    'project showcase',
    'demo apps',
    'example projects',
    'what can i build',
    'portfolio templates',
    'community templates',
  ],

  // REST Collections
  '/docs/posts': [
    'posts collection',
    'blog posts',
    'articles',
    'dummy articles',
    'fake feed',
    'create blog post',
    'edit post',
    'delete post',
    'like posts',
    'news feed',
    'get /posts',
    'post /posts',
  ],
  '/docs/comments': [
    'comments collection',
    'post replies',
    'user reviews',
    'discussion threads',
    'leave a comment',
    'feedback list',
    'get /comments',
    'post /comments',
  ],
  '/docs/users': [
    'users collection',
    'user profiles',
    'accounts',
    'fake users list',
    'dummy profiles',
    'generate mock people',
    'customer directory',
    'get /users',
    'post /users',
  ],
  '/docs/todos': [
    'todos collection',
    'task list',
    'todo app backend',
    'checklist items',
    'completed tasks',
    'mark as done',
    'get /todos',
    'post /todos',
    'patch /todos',
  ],
  '/docs/auth': [
    'authentication jwt',
    'how to fake login',
    'user sign in',
    'register new account',
    'auth token',
    'bearer token header',
    'post /auth/login',
    'post /auth/register',
    'get /auth/me',
    'jwt simulation',
    'protected route testing',
    'refresh token',
    'login simulation',
    'jwt expiration simulation',
    'x-simulate-jwt-expiry',
    'token rotation',
    'refresh token reuse detection',
    'refresh_token_reused',
    'clock skew drift',
    'x-simulate-clock-skew',
    'axios 401 interceptor retry loop',
    'short lived jwt testing',
  ],
  '/docs/custom': [
    'custom collections',
    'create my own resource',
    'dynamic database',
    'custom products',
    'custom orders',
    'post /custom/products',
    'arbitrary json storage',
    'schemaless rest api',
    'store any data',
  ],
  '/docs/avatars': [
    'media and avatars',
    'dummy profile picture',
    'random avatar generator',
    'svg image placeholder',
    'vector user photos',
    '/public/avatars/seed',
    'image urls for mock apps',
    'gravatar alternative',
  ],

  // GraphQL
  '/docs/graphql': [
    'graphql gateway',
    'graphiql ide',
    'graphql query',
    'graphql mutation',
    'apollo client mock',
    'relay mock',
    'test graphql endpoint',
    'in-browser graphql sandbox',
  ],

  // Downloads & Specs
  '/docs/collections/openapi': [
    'openapi 3.0 spec',
    'swagger yaml json',
    'download openapi',
    'export api spec',
    'openapi generator',
  ],
  '/docs/collections/postman': [
    'postman collection',
    'download postman json',
    'import to postman',
    'postman v2.1',
    'test in postman',
  ],
  '/docs/collections/bruno': [
    'bruno collection',
    'download bruno',
    'open source api client',
    'use bruno with playground api',
  ],
  '/docs/collections/insomnia': [
    'insomnia collection',
    'download insomnia json',
    'import to insomnia',
    'kong insomnia',
  ],
  '/docs/sdk': [
    'official typescript sdk',
    'playground-api npm',
    'javascript client library',
    'node sdk',
    'zero dependency sdk',
    'react hook api client',
    'nextjs sdk',
    'vue sdk',
    'isomorphic api client',
    'npm install playground-api',
  ],
  '/docs/collections/typescript': [
    'typescript types',
    'download .d.ts',
    'type definitions',
    'typescript interfaces',
    'strong typing mock',
    'sdk declarations',
  ],
  '/docs/collections/csv-excel': [
    'csv export',
    'excel spreadsheet download',
    'xlsx export',
    'download posts csv',
    'download users excel',
    'table data export',
    'spreadsheet mock data',
    'flat dot notation',
    'rfc 4180 csv',
    'tanstack table data',
    'pandas mock dataframe',
  ],
  '/docs/payments': [
    'payments api',
    'mock payment gateway',
    'stripe mock',
    'stripe parity sandbox',
    'test credit card numbers',
    'fake credit card',
    '3d secure challenge',
    '3ds verification modal',
    'payment intents api',
    'hosted checkout session',
    'checkout session mock',
    'refunds api',
    'simulate declined card',
    'simulate insufficient funds',
    'simulate card expired',
    'receipt emails',
    'test payments in react',
  ],
  '/docs/uploads': [
    'file uploads',
    'multipart form data',
    'upload files',
    'bulk file upload',
    'cloudinary cdn sandbox',
    'mock s3 bucket',
    'mock cloud storage',
    'image upload mock',
    'upload progress bar',
    'file size limit 5mb',
    'batch size limit 25mb',
    'itemized bulk upload',
    'magic bytes validation',
    'blocked file extensions',
    'simulate upload latency',
    'playwright file upload',
  ],
  '/docs/graphql/subscriptions': [
    'graphql subscriptions',
    'graphql-ws',
    'websocket graphql',
    'apollo client subscriptions',
    'urql subscriptions',
    'realtime graphql sandbox',
    'postAdded subscription',
    'commentAdded subscription',
    'todoUpdated subscription',
    'graphql live queries',
    'reactive mock api',
  ],
  '/docs/rbac': [
    'rbac',
    'role based access control',
    'roles and permissions',
    'admin editor viewer guest',
    'simulate 403 forbidden',
    '403 forbidden testing',
    'scope permissions',
    'oauth scopes',
    'x-simulate-role',
    'x-simulate-scopes',
    'react route guard test',
    'nextjs auth middleware',
    'user permissions mock',
    'test personas admin editor',
    'permission matrix',
    'wildcard scopes',
  ],
  '/docs/analytics': [
    'analytics',
    'telemetry',
    'event tracking',
    'mock analytics api',
    'posthog mock',
    'mixpanel mock',
    'segment track',
    'batch event ingestion',
    'page view tracking',
    'conversion funnel testing',
    'playwright analytics assertion',
    'custom useanalytics hook',
    'event beacon simulator',
    'telemetry stream',
  ],
  '/docs/devtools': [
    'devtools extension',
    'chrome extension',
    'edge extension',
    'browser extension',
    'devtools companion panel',
    'playground api extension',
    'f12 devtools mock',
    'latency slider extension',
    'error injection extension',
    'reset sandbox extension',
    'download extension zip',
    'chrome web store',
  ],
};
