'use client';

import React, { useState } from 'react';
import { Icon } from '@iconify/react';
import { InteractiveConsole } from '@/components/docs/InteractiveConsole';
import { CodeBlock } from '@/components/docs/CodeBlock';

interface InAppAlert {
  id: string;
  title: string;
  content: string;
  type: 'info' | 'success' | 'warning' | 'error';
  read: boolean;
  actionUrl?: string;
  created_at: string;
}

export default function InAppMessagesPage() {
  const [alerts, setAlerts] = useState<InAppAlert[]>([
    {
      id: 'msg_01',
      title: 'Scheduled Maintenance Notice',
      content: 'Database indexing will take place on Sunday at 02:00 UTC. Zero downtime expected.',
      type: 'warning',
      read: false,
      actionUrl: '/docs/status',
      created_at: '10m ago',
    },
    {
      id: 'msg_02',
      title: 'New API Key Provisioned',
      content: 'A new secret key "sk_live_98...21" was generated by Administrator.',
      type: 'info',
      read: false,
      actionUrl: '/docs/auth',
      created_at: '1h ago',
    },
    {
      id: 'msg_03',
      title: 'Monthly Subscription Renewed',
      content: 'Your Pro Developer Plan was successfully charged $29.00 USD.',
      type: 'success',
      read: true,
      actionUrl: '/docs/payments',
      created_at: '1d ago',
    },
  ]);

  const [activeToast, setActiveToast] = useState<InAppAlert | null>(null);

  const toggleRead = (id: string) => {
    setAlerts(prev =>
      prev.map(a => (a.id === id ? { ...a, read: !a.read } : a))
    );
  };

  const triggerSampleToast = (type: 'info' | 'success' | 'warning' | 'error') => {
    const toast: InAppAlert = {
      id: `toast_${Date.now()}`,
      title: `${type.toUpperCase()} Notification`,
      content: `Live toast alert triggered at ${new Date().toLocaleTimeString()}`,
      type,
      read: false,
      created_at: 'Just now',
    };
    setActiveToast(toast);
    setTimeout(() => setActiveToast(null), 4000);
  };

  const unreadCount = alerts.filter(a => !a.read).length;

  return (
    <div className="space-y-12 w-full text-slate-900 pb-16">
      {/* 1. Page Header */}
      <div id="overview" className="space-y-4 scroll-mt-20">
        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-amber-50 text-amber-700 text-xs font-semibold uppercase tracking-wider border border-amber-200">
          <Icon icon="ph:bell-ringing-bold" className="w-3.5 h-3.5" />
          <span>Virtual Communications</span>
        </div>

        <h1 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold tracking-tight text-slate-900 leading-[1.15]">
          In-App Notifications &amp; Alerts Feed
        </h1>

        <p className="text-base sm:text-lg text-slate-600 leading-relaxed max-w-4xl">
          Simulate in-app notification centers, toast alert streams, and persistent announcement banners.
          Model read/unread status updates, severity categories (<code className="font-mono text-xs text-blue-600">info</code>, <code className="font-mono text-xs text-emerald-600">success</code>, <code className="font-mono text-xs text-amber-600">warning</code>, <code className="font-mono text-xs text-rose-600">error</code>),
          and interactive deep links.
        </p>

        <div className="flex flex-wrap gap-2 pt-2">
          <a
            href="#notification-feed"
            className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg text-xs font-semibold bg-amber-600 text-white hover:bg-amber-700 transition-colors shadow-xs"
          >
            <Icon icon="ph:bell-simple-bold" className="w-4 h-4" />
            Live Notification Center
          </a>
          <a
            href="#interactive-consoles"
            className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg text-xs font-semibold bg-slate-100 text-slate-700 hover:bg-slate-200 transition-colors border border-slate-200"
          >
            <Icon icon="ph:terminal-window-bold" className="w-4 h-4" />
            API Consoles
          </a>
        </div>
      </div>

      {/* 2. Live Interactive Notification Center Simulation */}
      <div id="notification-feed" className="p-6 rounded-2xl bg-white border border-slate-200 shadow-xs space-y-6 scroll-mt-20">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-100 pb-4">
          <div>
            <h2 className="text-lg font-bold text-slate-900">Interactive Notification Center</h2>
            <p className="text-xs text-slate-500">
              Test read/unread state toggles and trigger live simulated toast banners.
            </p>
          </div>

          {/* Quick Toast Trigger Buttons */}
          <div className="flex flex-wrap items-center gap-1.5">
            <span className="text-xs font-semibold text-slate-500 mr-1">Simulate Toast:</span>
            <button
              type="button"
              onClick={() => triggerSampleToast('success')}
              className="px-2.5 py-1 rounded-lg text-xs font-semibold bg-emerald-50 text-emerald-700 border border-emerald-200 hover:bg-emerald-100 cursor-pointer"
            >
              Success
            </button>
            <button
              type="button"
              onClick={() => triggerSampleToast('warning')}
              className="px-2.5 py-1 rounded-lg text-xs font-semibold bg-amber-50 text-amber-700 border border-amber-200 hover:bg-amber-100 cursor-pointer"
            >
              Warning
            </button>
            <button
              type="button"
              onClick={() => triggerSampleToast('error')}
              className="px-2.5 py-1 rounded-lg text-xs font-semibold bg-rose-50 text-rose-700 border border-rose-200 hover:bg-rose-100 cursor-pointer"
            >
              Error
            </button>
          </div>
        </div>

        {/* Floating Toast Notification Preview (if active) */}
        {activeToast && (
          <div className="p-4 rounded-xl border shadow-lg bg-white flex items-center justify-between gap-3 animate-in fade-in slide-in-from-top-4 duration-200 border-indigo-200 ring-2 ring-indigo-500/20">
            <div className="flex items-center gap-3">
              <div
                className={`w-8 h-8 rounded-lg flex items-center justify-center font-bold text-xs ${
                  activeToast.type === 'success'
                    ? 'bg-emerald-100 text-emerald-700'
                    : activeToast.type === 'warning'
                    ? 'bg-amber-100 text-amber-700'
                    : activeToast.type === 'error'
                    ? 'bg-rose-100 text-rose-700'
                    : 'bg-blue-100 text-blue-700'
                }`}
              >
                <Icon icon="ph:bell-ringing-bold" className="w-4 h-4" />
              </div>
              <div>
                <h4 className="font-bold text-xs text-slate-900">{activeToast.title}</h4>
                <p className="text-[11px] text-slate-500">{activeToast.content}</p>
              </div>
            </div>
            <button
              type="button"
              onClick={() => setActiveToast(null)}
              className="text-slate-400 hover:text-slate-600 text-xs cursor-pointer"
            >
              Dismiss
            </button>
          </div>
        )}

        {/* Notification Feed List */}
        <div className="space-y-3">
          <div className="flex items-center justify-between text-xs text-slate-500 px-1">
            <span>Notification Feed</span>
            <span className="font-semibold text-slate-700">{unreadCount} Unread Alerts</span>
          </div>

          <div className="divide-y divide-slate-100 border border-slate-200 rounded-2xl overflow-hidden bg-white">
            {alerts.map(item => (
              <div
                key={item.id}
                className={`p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-4 transition-colors ${
                  !item.read ? 'bg-indigo-50/20' : 'hover:bg-slate-50/60'
                }`}
              >
                <div className="flex items-start gap-3">
                  <div
                    className={`w-2 h-2 rounded-full mt-1.5 shrink-0 ${
                      !item.read ? 'bg-indigo-600' : 'bg-transparent'
                    }`}
                  />
                  <div className="space-y-1">
                    <div className="flex items-center gap-2">
                      <span className="font-bold text-xs text-slate-900">{item.title}</span>
                      <span
                        className={`px-1.5 py-0.2 rounded text-[10px] font-bold uppercase tracking-wider ${
                          item.type === 'success'
                            ? 'bg-emerald-50 text-emerald-700 border border-emerald-200'
                            : item.type === 'warning'
                            ? 'bg-amber-50 text-amber-700 border border-amber-200'
                            : item.type === 'error'
                            ? 'bg-rose-50 text-rose-700 border border-rose-200'
                            : 'bg-blue-50 text-blue-700 border border-blue-200'
                        }`}
                      >
                        {item.type}
                      </span>
                    </div>
                    <p className="text-xs text-slate-600">{item.content}</p>
                    <span className="text-[10px] text-slate-400 font-mono block">{item.created_at}</span>
                  </div>
                </div>

                <div className="flex items-center gap-2 shrink-0 self-end sm:self-center">
                  {item.actionUrl && (
                    <a
                      href={item.actionUrl}
                      className="px-2.5 py-1 rounded-lg bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-semibold"
                    >
                      View
                    </a>
                  )}
                  <button
                    type="button"
                    onClick={() => toggleRead(item.id)}
                    className="px-2.5 py-1 rounded-lg border border-slate-200 hover:bg-slate-100 text-slate-600 text-xs font-medium cursor-pointer"
                  >
                    Mark as {item.read ? 'Unread' : 'Read'}
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* 3. Interactive Consoles */}
      <div id="interactive-consoles" className="space-y-6 scroll-mt-20">
        <div className="border-b border-slate-200 pb-3">
          <h2 className="text-xl sm:text-2xl font-extrabold text-slate-900">
            Interactive Consoles
          </h2>
          <p className="text-xs sm:text-sm text-slate-500 mt-1">
            Publish notifications to the sandbox feed and query unread counts.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="space-y-3">
            <h3 className="text-sm font-bold text-slate-900">1. Publish Notification</h3>
            <InteractiveConsole
              method="POST"
              path="/messages"
              title="Create In-App Message"
              initialBody={JSON.stringify(
                {
                  title: 'Security Scan Completed',
                  content: 'Zero vulnerabilities detected across your endpoints.',
                  type: 'success',
                  read: false,
                  actionUrl: '/docs/auth',
                },
                null,
                2
              )}
            />
          </div>

          <div className="space-y-3">
            <h3 className="text-sm font-bold text-slate-900">2. Query Notifications</h3>
            <InteractiveConsole
              method="GET"
              path="/messages"
              title="List In-App Notifications"
            />
          </div>
        </div>
      </div>

      {/* 4. Production Integration Recipes */}
      <div id="recipes" className="space-y-6 scroll-mt-20">
        <div className="border-b border-slate-200 pb-3">
          <h2 className="text-xl sm:text-2xl font-extrabold text-slate-900">
            Frontend Integration Recipe
          </h2>
          <p className="text-xs sm:text-sm text-slate-500 mt-1">
            React hook for streaming and displaying in-app alerts in real time.
          </p>
        </div>

        <CodeBlock
          language="typescript"
          code={`import { useState, useEffect } from 'react';

export function useInAppNotifications() {
  const [messages, setMessages] = useState<any[]>([]);

  useEffect(() => {
    // 1. Initial fetch of notifications
    fetch('https://playground.nileslabs.com/api/v1/messages')
      .then(res => res.json())
      .then(data => setMessages(data.data || []));

    // 2. Stream real-time alerts via SSE
    const es = new EventSource('https://playground.nileslabs.com/api/v1/stream');
    es.addEventListener('message.created', (event) => {
      const newAlert = JSON.parse(event.data);
      setMessages(prev => [newAlert, ...prev]);
    });

    return () => es.close();
  }, []);

  return { messages, unreadCount: messages.filter(m => !m.read).length };
}`}
        />
      </div>
    </div>
  );
}
