import { NextResponse } from 'next/server';
import config from '@/config/env';

export async function GET() {
  const base = config.publicApiUrl || 'https://playground.nileslabs.com/api/v1';
  const site = config.siteUrl || 'https://playground.nileslabs.com';

  const manifest = {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    name: 'Playground API',
    slug: 'playground-api',
    version: '1.0.0',
    category: [
      'mock-api',
      'api-sandbox',
      'developer-tool',
      'testing-tool',
      'graphql-sandbox',
      'e2e-testing-backend',
      'real-time-websocket-mock',
      'mock-payment-gateway',
      'virtual-email-sms-inbox',
      'mock-file-uploads',
    ],
    description:
      'Free, zero-configuration, stateful mock REST and GraphQL API sandbox for frontend development, prototyping, automated testing, and AI coding agents.',
    website: site,
    documentation: `${site}/docs`,
    repository: 'https://github.com/nileslabs/playground_api',
    license: 'MIT',
    api: {
      base_url: base,
      rest: true,
      graphql: true,
      graphql_endpoint: `${base}/graphql`,
      websocket_endpoint: `wss://${base.replace(/^https?:\/\//, '')}/ws`,
      sse_endpoint: `${base}/stream`,
    },
    authentication: {
      required: false,
      jwt_simulation: true,
      login_endpoint: '/auth/login',
      refresh_endpoint: '/auth/refresh',
      profile_endpoint: '/auth/me',
      rbac_roles: ['admin', 'editor', 'viewer', 'guest'],
    },
    state: {
      persistent: true,
      session_scoped: true,
      global_seed_data_mutable: false,
      retention_days: 10,
      max_overlay_records_per_resource: 30,
      reset_endpoint: '/session/reset',
      snapshot_export_endpoint: '/session/snapshot',
      snapshot_import_endpoint: '/session/snapshot',
      shareable_sandbox_url: `${site}/docs/sandbox-sync`,
    },
    features: [
      'stateful-crud-persistence',
      'pagination',
      'cursor-pagination',
      'relational-filtering',
      'full-text-search',
      'multi-field-sorting',
      'network-delay-simulation',
      'http-error-simulation',
      'rate-limit-simulation',
      'chaos-network-simulation',
      'jwt-expiration-simulation',
      'role-based-access-control',
      'mock-payment-gateway',
      'virtual-email-sms-inbox',
      'multipart-file-uploads',
      'outgoing-webhooks-dispatcher',
      'real-time-websockets-chat',
      'graphql-gateway',
      'graphql-subscriptions',
      'custom-collections',
      'svg-avatar-generation',
      'svg-thumbnail-generation',
      'session-snapshots',
      'shareable-sandbox-urls',
      'official-typescript-sdk',
      'devtools-browser-extension',
      'csv-excel-export',
      'openapi-export',
      'postman-export',
      'bruno-export',
      'insomnia-export',
      'typescript-definitions',
    ],
    collections: [
      { name: 'posts', path: '/posts', count: 100, relational: ['user_id', 'comments'] },
      { name: 'comments', path: '/comments', count: 300, relational: ['post_id'] },
      { name: 'users', path: '/users', count: 25, relational: ['posts', 'todos'] },
      { name: 'todos', path: '/todos', count: 125, relational: ['user_id', 'completed'] },
      { name: 'auth', path: '/auth', type: 'JWT Simulation' },
      { name: 'payments', path: '/payments', type: 'Mock Stripe Gateway' },
      { name: 'emails', path: '/emails', type: 'Virtual Email Sandbox' },
      { name: 'sms', path: '/sms', type: 'Virtual SMS Sandbox' },
      { name: 'uploads', path: '/uploads', type: 'Multipart Storage CDN' },
      { name: 'webhooks', path: '/webhooks', type: 'Outgoing Dispatcher' },
      { name: 'custom', path: '/custom/:collection', type: 'Dynamic Schema-less' },
      { name: 'avatars', path: '/avatars/:seed', type: 'Vector SVG Generator' },
      { name: 'thumbnails', path: '/thumbnails/:seed', type: 'Vector SVG Image Helper' },
    ],
    audience: [
      'frontend-developers',
      'mobile-developers',
      'qa-engineers',
      'educators',
      'ai-coding-agents',
    ],
    specs: {
      openapi: `${base}/downloads/openapi.json`,
      postman: `${base}/downloads/postman.json`,
      bruno: `${base}/downloads/bruno.json`,
      insomnia: `${base}/downloads/insomnia.json`,
      typescript: `${base}/downloads/playground-api.d.ts`,
      sdk_npm: 'playground-api',
      llms: `${site}/llms.txt`,
      llms_full: `${site}/llms-full.txt`,
    },
  };

  return NextResponse.json(manifest, {
    headers: {
      'Content-Type': 'application/json; charset=utf-8',
      'Cache-Control': 'public, max-age=3600, s-maxage=86400',
    },
  });
}
